//! Shared keyring rotation helper for profile rotate-key commands.
//!
//! [`rotate_hmac_like_key`] generates 32 CSPRNG bytes for HMAC-keyed
//! operations (attestation, audit-log chain root, counterparty cache).  The
//! bytes are consumed as `HMAC-SHA256(key, …)`.  The stored value is URL-safe
//! base64 (no padding) encoded; the path delegates to
//! [`stellar_agent_network::keyring::rotate_keyring_secret_32`], the same
//! primitive used by `stellar-agent-nonce::rotate_nonce_key`.
//!
//! # Self-custodial conformance
//!
//! The helper never returns, logs, or stores the raw key bytes outside the
//! keyring; the zeroization discipline is inherited from the shared network
//! helper.
//!
//! # Key kind naming
//!
//! `caller_tag` is used only in `tracing::debug!` messages for operator
//! forensics; it never appears in the keyring entry itself.

use stellar_agent_core::{error::WalletError, profile::schema::KeyringEntryRef};
use stellar_agent_network::keyring::rotate_keyring_secret_32;

// ─────────────────────────────────────────────────────────────────────────────
// HMAC-key path (3 rotators: attestation, audit, counterparty)
// ─────────────────────────────────────────────────────────────────────────────

/// Generates a fresh 32-byte HMAC key and atomically replaces the keyring
/// entry identified by `entry_ref`.
///
/// The new key is generated by
/// [`rotate_keyring_secret_32`] via `OsRng::fill_bytes` (CSPRNG) and encoded
/// as URL-safe base64 (no padding) before storage.  Calling this when no entry
/// exists (first-run) succeeds by creating the entry.  Calling it when an entry
/// exists replaces the value atomically via `set_password`.
///
/// **This helper is for HMAC keys only.**  The policy-file owner key is an
/// ed25519 key enrolled via `stellar-agent profile enroll-owner-key`, not an
/// HMAC key.
///
/// `caller_tag` appears only in `tracing::debug!` messages; it is never
/// written to the keyring.
///
/// # Errors
///
/// - [`WalletError::Auth`] with the keyring failure classified by
///   [`stellar_agent_network::keyring::classify_keyring_error`]:
///   `KeyringInteractiveSessionRequired` when the Windows Credential Manager
///   is unreachable from a non-interactive session, `KeyringPlatformError`
///   for other backend failures, and `KeyringNotFound` when the platform
///   keyring is unavailable or the entry cannot be opened.
///
/// # Panics
///
/// Never panics.
pub(super) fn rotate_hmac_like_key(
    entry_ref: &KeyringEntryRef,
    caller_tag: &str,
) -> Result<(), WalletError> {
    // The shared helper classifies keyring failures — surface its error
    // unchanged so environmental causes (a non-interactive Windows session)
    // keep their typed code instead of collapsing into "not found".
    rotate_keyring_secret_32(&entry_ref.service, &entry_ref.account).inspect_err(|e| {
        tracing::debug!(
            error = %e,
            caller = caller_tag,
            "shared HMAC-like key rotation failed"
        );
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        reason = "test-only; panics acceptable in unit tests"
    )]

    use base64::Engine as _;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use keyring_core::Entry as KeyringEntry;
    use serial_test::serial;
    use stellar_agent_test_support::keyring_mock;

    use super::*;

    /// Rotates the HMAC key for the given entry ref and returns the stored base64
    /// string.  Private to this module.
    fn rotate_hmac_and_read(entry_ref: &KeyringEntryRef) -> String {
        rotate_hmac_like_key(entry_ref, "test").expect("rotation ok");
        let entry = KeyringEntry::new(&entry_ref.service, &entry_ref.account).unwrap();
        entry.get_password().expect("key stored")
    }

    #[test]
    #[serial]
    fn rotate_creates_32_byte_key() {
        keyring_mock::install().expect("mock store");
        let entry_ref = KeyringEntryRef::new("stellar-agent-audit-key-ops-test", "default");

        let stored = rotate_hmac_and_read(&entry_ref);
        let decoded = URL_SAFE_NO_PAD.decode(stored.as_bytes()).unwrap();
        assert_eq!(decoded.len(), 32, "key must be exactly 32 bytes");
    }

    #[test]
    #[serial]
    fn rotate_overwrites_existing_key() {
        keyring_mock::install().expect("mock store");
        let entry_ref = KeyringEntryRef::new("stellar-agent-key-ops-overwrite", "default");

        let first = rotate_hmac_and_read(&entry_ref);
        let second = rotate_hmac_and_read(&entry_ref);

        assert_ne!(first, second, "rotation must produce a fresh key");
    }

    /// The classified keyring failure must pass through unchanged: a
    /// non-interactive Windows session (`ERROR_NO_SUCH_LOGON_SESSION` on the
    /// `set_password` write) surfaces as
    /// `auth.keyring_interactive_session_required` from every rotate-*
    /// command routed through this helper, not as a generic
    /// `auth.keyring_not_found` claiming the entry is missing.
    #[test]
    #[serial]
    fn rotate_surfaces_interactive_session_required_on_windows_write_failure() {
        keyring_mock::install().expect("mock store");
        let entry_ref = KeyringEntryRef::new("stellar-agent-key-ops-no-logon", "default");
        keyring_mock::inject_no_logon_session(&entry_ref.service, &entry_ref.account)
            .expect("inject");

        let err = rotate_hmac_like_key(&entry_ref, "test").expect_err("rotation must fail");
        assert_eq!(err.code(), "auth.keyring_interactive_session_required");
        assert!(
            err.message().contains("STELLAR_AGENT_KEYRING_BACKEND"),
            "the message must name the headless escape hatch: {}",
            err.message()
        );
    }

    #[test]
    #[serial]
    fn rotated_key_is_valid_base64() {
        keyring_mock::install().expect("mock store");
        let entry_ref = KeyringEntryRef::new("stellar-agent-key-ops-b64", "default");

        let stored = rotate_hmac_and_read(&entry_ref);
        let bytes = URL_SAFE_NO_PAD
            .decode(stored.as_bytes())
            .expect("valid URL-safe base64");
        assert_eq!(bytes.len(), 32);
    }
}
