//! Cross-implementation vectors: the preimages built here equal the ones the
//! released `@stellar/stellar-sdk` builds.
//!
//! `interop/stellar-sdk-v17/fixtures/` holds one envelope type 9 and one
//! envelope type 10 preimage generated by the pinned SDK's
//! `buildAuthorizationEntryPreimage` from fixed inputs, together with the SDK's
//! SHA-256 of the preimage. Each test rebuilds the preimage from the inputs
//! through [`build_auth_preimage`] and asserts byte and hash equality. The CI
//! job `sdk-v17-interop` proves the fixtures still match the pinned SDK.

#![allow(
    clippy::expect_used,
    clippy::panic,
    reason = "a fixture mismatch must stop with the violated invariant"
)]

use sha2::{Digest, Sha256};
use stellar_agent_soroban_auth::{
    AuthCredentialsVersion, auth_signature_payload, build_auth_preimage, preimage_parts,
};
use stellar_xdr::{
    AccountId, ContractId, Hash, HashIdPreimage, InvokeContractArgs, Limits, PublicKey, ReadXdr,
    ScAddress, ScVal, SorobanAuthorizedFunction, SorobanAuthorizedInvocation, Uint256, WriteXdr,
};

const PREIMAGE_V1: &str =
    include_str!("../../../interop/stellar-sdk-v17/fixtures/preimage-v1.json");
const PREIMAGE_V2: &str =
    include_str!("../../../interop/stellar-sdk-v17/fixtures/preimage-v2.json");

fn field<'a>(fixture: &'a serde_json::Value, name: &str) -> &'a serde_json::Value {
    fixture
        .get(name)
        .unwrap_or_else(|| panic!("fixture field {name} is present"))
}

fn text<'a>(fixture: &'a serde_json::Value, name: &str) -> &'a str {
    field(fixture, name)
        .as_str()
        .unwrap_or_else(|| panic!("fixture field {name} is a string"))
}

fn lower_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// Rebuilds the fixture's preimage from its inputs and asserts it equals the
/// SDK's bytes and hash.
fn assert_fixture(json: &str, version: AuthCredentialsVersion) {
    let fixture: serde_json::Value = serde_json::from_str(json).expect("fixture is JSON");
    assert_eq!(
        field(&fixture, "envelopeType").as_u64(),
        Some(u64::from(version.envelope_type_number())),
        "fixture envelope type"
    );

    let network_id: [u8; 32] = Sha256::digest(text(&fixture, "networkPassphrase")).into();
    let nonce = field(&fixture, "nonce").as_i64().expect("nonce is an i64");
    let expiration = u32::try_from(
        field(&fixture, "signatureExpirationLedger")
            .as_u64()
            .expect("expiration is an integer"),
    )
    .expect("expiration fits u32");
    let account = stellar_strkey::ed25519::PublicKey::from_string(text(&fixture, "address"))
        .expect("address is a G-strkey");
    let address = ScAddress::Account(AccountId(PublicKey::PublicKeyTypeEd25519(Uint256(
        account.0,
    ))));
    let contract = stellar_strkey::Contract::from_string(text(&fixture, "contract"))
        .expect("contract is a C-strkey");
    let args: Vec<ScVal> = field(&fixture, "args")
        .as_array()
        .expect("args is an array")
        .iter()
        .map(|arg| {
            ScVal::from_xdr_base64(arg.as_str().expect("arg is base64"), Limits::none())
                .expect("arg is a base64 ScVal")
        })
        .collect();
    let invocation = SorobanAuthorizedInvocation {
        function: SorobanAuthorizedFunction::ContractFn(InvokeContractArgs {
            contract_address: ScAddress::Contract(ContractId(Hash(contract.0))),
            function_name: text(&fixture, "functionName")
                .try_into()
                .expect("function name is a ScSymbol"),
            args: args.try_into().expect("args fit VecM"),
        }),
        sub_invocations: Vec::new().try_into().expect("empty sub-invocations"),
    };

    let built = build_auth_preimage(version, network_id, nonce, expiration, &address, invocation);

    let sdk_preimage = text(&fixture, "preimageXdr");
    assert_eq!(
        built
            .to_xdr_base64(Limits::none())
            .expect("built preimage encodes"),
        sdk_preimage,
        "the built preimage bytes must equal the SDK preimage"
    );
    let decoded = HashIdPreimage::from_xdr_base64(sdk_preimage, Limits::none())
        .expect("SDK preimage decodes");
    let expected_address = match version {
        AuthCredentialsVersion::V1 => None,
        AuthCredentialsVersion::V2 => Some(&address),
    };
    assert_eq!(
        preimage_parts(&decoded),
        Some((version, network_id, expected_address))
    );

    let payload = auth_signature_payload(&built).expect("payload hashes");
    assert_eq!(
        lower_hex(&payload),
        text(&fixture, "payloadHex"),
        "the payload must equal the SDK hash"
    );
}

#[test]
fn case_9_preimage_matches_the_sdk() {
    assert_fixture(PREIMAGE_V1, AuthCredentialsVersion::V1);
}

#[test]
fn case_10_preimage_matches_the_sdk() {
    assert_fixture(PREIMAGE_V2, AuthCredentialsVersion::V2);
}
